In [2]:
import numpy as np


In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [6]:
a2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

a2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
type(a2d)

numpy.ndarray

In [9]:
a = np.int8
a


numpy.int8

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10, 20, 0.4)

array([10. , 10.4, 10.8, 11.2, 11.6, 12. , 12.4, 12.8, 13.2, 13.6, 14. ,
       14.4, 14.8, 15.2, 15.6, 16. , 16.4, 16.8, 17.2, 17.6, 18. , 18.4,
       18.8, 19.2, 19.6])

In [ ]:
#1 dan 4 gacha bolgan kesmani 10 ta bolakka boladi
np.linspace(1, 4, 10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [ ]:
#2 ga 3 lik olchamdagi 0 lardan iborat array qaytaradi
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#2ga 3 lik matritsa chiqaradi, 1 lardan iborat
ones = np.ones((2, 3), dtype = int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
ones.astype(float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
sevens = np.full((2, 7), fill_value = 7)
sevens

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [ ]:
#diagonal boyicha 1 lar bor matrix
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])